unit Msg;

interface

const

wmDescAlreadyPresent='Opis ju¿ istnieje na liœcie';

wmConfirmExit='PotwierdŸ wyjœcie';
wmValueOver100='Wartoœæ wagi powy¿ej 100%';
wmValueIs0='Wartoœæ wagi nie ma znaczenia (0 %)';
wmValueUnknown='Wartoœæ wagi nie zosta³a podana';
wmEvaluationUnknown='Sposób oceny nie zosta³ podany';
wmDescEmpty='Opis kryterium nie zosta³ podany';
mValueOver32767='Wartoœæ powy¿ej 32767 (maks.)';
wmWeightsSumOver100='Suma wag powy¿ej 100%';
wmWeightsSumUnder100='Suma wag poni¿ej 100%';
wmPointsOverMax='Wartoœæ powy¿ej maksymalnej iloœci punktów';
wmDifferentPwd='Podane has³a s¹ odmienne';
wmIncorrectPwd='Has³o nieprawid³owe';

mUnknownQuantityValue='Wartoœæ nie znana';
mQuantityValueNotSpecified='Wartoœæ nie zosta³a podana';

mMaxPtsNumIs0='Iloœæ punktów nie mo¿e byæ 0';
mTendersNumIs0='Iloœæ ofert nie mo¿e byæ 0';
mUnknownQuantity='Iloœæ ofert nie zosta³a podana';
mEmptyMembersList='Sk³ad komisji jest pusty';
mEmptyKriteriumsList='Lista kryteriów jest pusta';
mNoMaxPoints='Iloœæ punktów nie zosta³a podana';

imNextTender='Nastêpna oferta';
imLastCell='Ostatnie kryterium';

wmSaveData='Czy zachowaæ dane ?';

wmDifferentFileKey='Kod zbioru nie jest zgodny z t¹ wersj¹';
wmIncompatibleFile='Zbiór nie jest zgodny z t¹ wersj¹. Zbiór nie mo¿e byæ odczytany';
wmFileAccessDenied='Nie ma dostêpu do pliku';
wmReadBeyondEnd='Zbiór nie w³aœciwy (b³¹d 100)';

implementation

end.
