unit Msg2;

interface
const
  mChooseObjectKind='';
  mUnableToLoadDLL='Nie mo¿na ³adowaæ ';

{warnings}
  wmUserNameEmpty='Pole "U¿ytkownik" nie mo¿e byæ puste';
  wmPasswordEmpty='Pole "Has³o" nie mo¿e byæ puste';
  wmLoginIncorrect='Login nie prawid³owy';
  wmOldPwdIncorrect='Stare has³o nieprawid³owe';
  wmDifferentPwd='B³êdne nowe has³o';

  wmSecurityFileNotFound='Zbiór hase³ nie znaleziony';
  wmInstallAgain='Zainstaluj ponownie';
  wmCantOpenSecurityFile='Nie mo¿na otwieraæ zbioru hase³';

  wmFileNotFound='Zbiór nie znaleziony';
  wmDirNotFound='Katalog nie znaleziony';
  wmFileAccessDenied='Nie ma dostêpu do pliku';
  wmFileAlreadyLoaded='Zbiór juz za³adowany';
  wmReadBeyondEnd='Zbiór nie w³aœciwy (b³¹d 100)';
  wmNoDirSelected='Najpierw wybierz katalog';
  wmDeleteWholeDir='Katalog i zbiory w nim bêd¹ wszystkie usuniête!';
  wmTryAgain='Ponów próbê';
  wmFileNotDeleted='Zbiór nie usuniêty';
  wmNoDirsForUser='Nie ma bazych danych dla tego u¿ytkownika';
  wmNoUserSelected='Najpierw wybierz u¿ytkownika';
  wmUserEmpty='Pole "Nazwa u¿ytkownika" nie mo¿e byæ puste';
  wmUserAlreadyExists='U¿ytkownik ju¿ istnieje';
  wmEndDateBeforeStartDate='Data zakoñczenia jest wczeœniejsza ni¿ data rozpoczêcia';
  wmIncorrectDate='Data nieprawid³owa';
  wmOpenDefaultFile='£aduje zbiór domyœlny';
  wmSiwzToBasicValues='Podstawowe wartoœci w polach';
  wmOpenDateBeforeSkladDate='Data otwarcia jest wczeœniejsza ni¿ data z³o¿enia';

  wmNoPointsSelectedArt71='Okolicznoœci nie zosta³e wybrane';

  wmIdEmpty='Pole "Identyfikator" jest puste';
  wmDescEmpty='Pole "Opis" jest puste';
  wmNewDocument='Nowy identyfikator. Tworzyæ now¹ SIWZ ?';


  wmGetPermit='Nale¿y uzyskaæ zgodê Prezesa Urzêdu Zamówieñ Publicznych';
  wmTimeError='Niew³aœciwa godzina';

wmIdAlreadyPresent='Identyfikator ju¿ istnieje.';
wmDescAlreadyPresent='Opis ju¿ istnieje.';
wmConfirmExit='PotwierdŸ wyjœcie';
wmValueOver100='Wartoœæ wagi powy¿ej 100%';
wmValueIs0='Wartoœæ wagi nie ma znaczenia (0 %)';
wmValueUnknown='Wartoœæ wagi nie znana';
wmValueOver32767='Wartoœæ powy¿ej 32767 (maks.)';
wmWeightsSumOver100='Suma wag powy¿ej 100%';
wmWeightsSumUnder100='Suma wag poni¿ej 100%';

emCantOpenDB='Otwarcie bazy danych jest niemo¿liwe';
emIncompatibleFile='Zbiór nie jest zgodny z t¹ wersj¹. Zbiór nie mo¿e byæ odczytany';
emIncompatibleDefFile='Zbiór domyœlny nie jest zgodny z t¹ wersj¹. Zbiór nie mo¿e byæ odczytany';

cmClosePrg='Naciœniêcie OK zakoñczy program';
implementation

end.
