unit Wyb1;

interface

uses WinTypes, WinProcs, Classes, Graphics, Forms, Controls, Buttons,
  StdCtrls, ExtCtrls, WybTryb;

type
  TWyb1Dlg = class(TForm)
    PanelBottom2: TPanel;
    Panel1: TPanel;
    Panel11: TPanel;
    Label1: TLabel;
    Label3: TLabel;
    Label2: TLabel;
    Panel12: TPanel;
    Label4: TLabel;
    Label5: TLabel;
    Label6: TLabel;
    YesBtn: TBitBtn;
    NoBtn: TBitBtn;
    CancelBtn: TBitBtn;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Wyb1Dlg: TWyb1Dlg;

implementation

{$R *.DFM}

end.
