program Obo;

uses
  Forms,
  Obotest in 'OBOTEST.PAS' {Form1},
  Siwzini in '\ZAMPUB2\SIWZINI.PAS',
  Zp1 in 'ZP1.PAS' {Zp1Dlg},
  Zp11 in 'ZP11.PAS' {Zp11Dlg},
  Zp12 in 'ZP12.PAS' {ZP12Dlg},
  Zp13 in 'ZP13.PAS' {Zp13Dlg},
  Zp14 in 'ZP14.PAS' {Zp14Dlg},
  Zp21 in 'ZP21.PAS',
  Zp31 in 'ZP31.PAS' {Zp31Dlg},
  Zp41 in 'ZP41.PAS' {Zp41Dlg},
  Zp42 in 'ZP42.PAS' {Zp42Dlg},
  Zp43 in 'ZP43.PAS' {Zp43Dlg},
  Zp44 in 'ZP44.PAS' {ZP44Dlg},
  Zp45 in 'ZP45.PAS' {ZP45Dlg},
  Zp46 in 'ZP46.PAS' {ZP46Dlg},
  Zp54 in 'ZP54.PAS' {Zp54Dlg},
  Zp61 in 'ZP61.PAS' {Zp61Dlg},
  Zp71 in 'ZP71.PAS' {Zp71Dlg},
  Zp81 in 'ZP81.PAS' {ZP81Dlg},
  Zp210 in 'ZP210.PAS' {Zp210Dlg},
  Zp150 in 'ZP150.PAS' {Zp150Dlg},
  Zp141 in 'ZP141.PAS' {Zp141Dlg},
  Zp140 in 'ZP140.PAS' {Zp140Dlg},
  Zp170 in 'ZP170.PAS' {Zp170Dlg},
  Zp121 in 'ZP121.PAS' {Zp121Dlg},
  Zp120 in 'ZP120.PAS' {Zp120Dlg},
  Zp110 in 'ZP110.PAS' {Zp110Dlg},
  UserUnit in '\ZAMPUB2\ADMIN\USERUNIT.PAS',
  Zp130 in 'ZP130.PAS' {Zp130Dlg},
  Zp160 in 'ZP160.PAS' {Zp160Dlg},
  Unit2 in 'UNIT2.PAS';

{$R *.RES}

begin
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
